---
title: "Public Opinion - Party - Environment Spending"
output: html_notebook
---

# Master Thesis - Vi Le


## Load libraries - Initial Setup

```{r library, include = TRUE, message = FALSE}
rm(list = ls())  # Clean the global environment
#install.packages("here")
#install.packages("pacman")

library(pacman)

pacman::p_load("tidyverse","haven", "car","countrycode", "openxlsx", "lavaan", "knitr","semTools", "ragg", "sjmisc", "sjPlot", "gt")  # Load libraries

library(here)
options(encoding = "UTF-8")
```

## Read files

```{r read, include = TRUE, message = FALSE}

# Environment Module
env00 <- read_dta(here::here("Vi Le - Master Thesis","ZA3440_Envi2000.dta"))
env10 <- read_dta(here::here("Vi Le - Master Thesis","ZA5500_Envi2010.dta"))

# CHES
ches10 <- read.csv(here::here("Vi Le - Master Thesis","2010_CHES_dataset_means.csv", na.strings = ""))
ches14 <- read.csv(here::here("Vi Le - Master Thesis","2014_CHES_dataset_means.csv", na.strings = ""))
seat1 <- read.xlsx(here::here("Vi Le - Master Thesis","Percentage-of-seats-in-parliaments.xlsx",na.strings="", sheet=1))
seat2 <- read.xlsx(here::here("Vi Le - Master Thesis","Percentage-of-seats-in-parliaments.xlsx",na.strings="", sheet=2))

# Government spending 
gspend <- read.csv(here::here("Vi Le - Master Thesis","gov_10a_exp_1_Data.csv"))

# CO2 Emission
co2 <- read.table(file = here::here("Vi Le - Master Thesis","estat_t2020_rd300.tsv", sep = '\t', header = TRUE)) 

# Environment tax
gtax <- read.csv(here::here("Vi Le - Master Thesis","env_ac_tax_1_Data.csv"))

# GDP per Capita
gdp <- read.csv(here::here("Vi Le - Master Thesis","nama_10_pc_1_Data.csv"))

```

## Environment

```{r clean00, include = TRUE, message = FALSE}

env00 <- env00 %>% 
  dplyr::mutate(
    cntry = zap_labels(v3),
    wave = 2010,
    year = 2000,
    cntry = dplyr::recode(cntry, `2` = 276, `3` = 276, `4` = 826, `5` = 826, `6` = 840, `7` = 040, `8` = 348, `9` = 380, `10` = 372, `11` = 528, `12` = 578, `13` = 752, `14` = 203, `15` = 705, `16` = 616, `17` = 100, `18` = 643, `19` = 554, `20` = 124, `21` = 608, `22` = 276, `24` = 392, `25` = 724, `26` = 428, `30` = 620, `31` = 152, `32` = 208, `33` = 756, `37` = 246, `38` = 484),
    price = zap_labels(as.numeric(car::recode(v19, '1=5;2=4;3=3;4=2;5=1;else=NA'))),
    tax = zap_labels(as.numeric(car::recode(v20,'1=5;2=4;3=3;4=2;5=1;else=NA'))),
    cut = zap_labels(as.numeric(car::recode(v21,'1=5;2=4;3=3;4=2;5=1;else=NA')))
  ) 

env00 <- dplyr::select(env00, cntry, year, price, tax, cut, wave)



```

```{r clean10, include = TRUE, message = FALSE}
colnames(env10) <- tolower(colnames(env10))
env10 <- env10 %>%
  mutate(
    cntry = country,
    wave = 2014,
    year = 2010,
    price = zap_labels(as.numeric(car::recode(v29,'1=5;2=4;3=3;4=2;5=1;else=NA'))),
    tax = zap_labels(as.numeric(car::recode(v30,'1=5;2=4;3=3;4=2;5=1;else=NA'))),
    cut = zap_labels(as.numeric(car::recode(v31,'1=5;2=4;3=3;4=2;5=1;else=NA')))
  )

env10 <- dplyr::select(env10, cntry, year, price, tax, cut, wave)



# Merge and arrange

env <- rbind(env00,env10)
env <- env %>%
  arrange(cntry, wave)


```

## CHES
```{r ches10, include = TRUE, message = FALSE}
ches10 <- ches10 %>%
  mutate(
    cname = car::recode(cname, recodes = '"be" = "BEL"; "den" = "DNK"; "ger" = "DEU"; "gre" = "GRC";
                        "spa" = "ESP"; "fra" = "FRA"; "ire" = "IRL"; "it" = "ITA"; "neth" = "NLD"; 
                        "uk" = "GBR"; "por" = "PRT"; "aus" = "AUT"; "fin" = "FIN"; "swe" = "SWE"; 
                        "bul" = "BGR"; "cze" = "CZE"; "est" = "EST"; "hun" = "HUN"; "LAT" = "LVA"; 
                        "lith" = "LTU"; "pol" = "POL"; "rom" = "ROU"; "slo" = "SVK"; "sle" = "SVN";
                        "cro" = "HRV"; "tur" = "TUR"; "nor" = "NOR"; "swi" = "CHE"; else = NA'),
    cntry = countrycode(cname, origin = "iso3c", destination = "iso3n"),
    env = environment,
    pname = party_name,
    pid = party_id, 
    year = 2010, 
    wave = 2010
  ) %>%
  arrange(cntry) %>%
  dplyr::select(cntry,year, wave, pname,pid,env)


```

```{r ches14, include = TRUE, message = FALSE}
ches14 <- ches14 %>%
  mutate(
    cname = car::recode(cname, recodes = '"bel" = "BEL"; "den" = "DNK"; "ger" = "DEU"; "gre" = "GRC";
                        "spa" = "ESP"; "fra" = "FRA"; "ire" = "IRL"; "it" = "ITA"; "net" = "NLD"; 
                        "uk" = "GBR"; "por" = "PRT"; "aus" = "AUT"; "fin" = "FIN"; "swe" = "SWE"; 
                        "bul" = "BGR"; "cze" = "CZE"; "est" = "EST"; "hun" = "HUN"; "lat" = "LVA"; 
                        "lith" = "LTU"; "pol" = "POL"; "rom" = "ROU"; "slo" = "SVK"; "sle" = "SVN";
                        "cro" = "HRV"; "tur" = "TUR"; "nor" = "NOR"; "swi" = "CHE"; "mal" = "MHL";
                        "lux" = "LUX"; "cyp"= "CYP"; else = NA'),
    cntry = countrycode(cname, origin = "iso3c", destination = "iso3n"),
    env = environment,
    pname = party_name,
    pid = party_id, 
    year = 2014, 
    wave = 2014
  ) %>%
  arrange(cntry) %>%
  dplyr::select(cntry,year, wave, pname,pid,env)

# Merge

ches <- rbind(ches10,ches14)
ches <- arrange(ches,cntry,wave)
```

## Seats
```{r seat, include=TRUE, message=FALSE}
seat1 <- seat1 %>%
  mutate(
    cntry = countrycode(Country, origin = "country.name", destination = "iso3n"),
    pname = Party.Abbrev,
    perseat = round(as.numeric(Percentage.of.seats.in.parliament),2),
    year = 2010, 
    wave = 2010
  ) %>%
  dplyr::select(cntry,year, wave, pname, perseat) %>% 
  arrange(cntry, wave)



seat2 <- seat2 %>%
  mutate(
    cntry = countrycode(Country, origin = "country.name", destination = "iso3n"),
    pname = Party.Abbrev,
    perseat = round(as.numeric(Percentage.of.seats.in.parliament),2),
    year = 2014,
    wave = 2014
  ) %>%
  dplyr::select(cntry, year, wave, pname, perseat) %>%
  arrange(cntry,wave)


seat <- rbind(seat1,seat2)
seat <- arrange(seat,cntry,wave)

  
# Move back to ches
ches <- filter(ches, cntry %in% seat$cntry)
ches <- arrange(ches,cntry,wave,pname)
seat <- arrange(seat,cntry,wave,pname)

party <- left_join(ches,seat, by = c("cntry","wave","pname", "year"))

party <- party[complete.cases(party$perseat),]
party <- party[complete.cases(party$env),]

party <- party %>%
  mutate(
    govpos = env*perseat/100
  )
govpos <- dplyr::select(party, cntry, wave, year, govpos)
govpos <- aggregate(govpos, by= list(govpos$cntry, govpos$year), FUN = sum)
govpos <- govpos %>%
  mutate(
    cntry = Group.1,
    year = Group.2,
    wave = year
  ) %>%
  dplyr::select(cntry, year, wave, govpos) %>%
  arrange(cntry, wave)
```


## Government spending
```{r spend, include=TRUE, message=FALSE}
gspend <- gspend %>%
  mutate(
    GEO = car::recode(GEO, '"Germany (until 1990 former territory of the FRG" = "Germany"'),
    cntry = countrycode(GEO, origin = "country.name", destination = "iso3n", nomatch = NULL),
    year = TIME,
    spend = Value, 
    wave = year
  ) %>%
  arrange(cntry,year) %>%
  dplyr::select(cntry,year,spend) %>%
  filter(year %in% c(2010,2014)& cntry %in% seat$cntry) %>%
  mutate(
    wave = year
  )

```



## Environment tax revenue
```{r tax, include=TRUE, message=FALSE}
gtax <- gtax %>%
  mutate(
    GEO = car::recode(GEO, '"Germany (until 1990 former territory of the FRG" = "Germany"'),
    cntry = countrycode(GEO, origin = "country.name", destination = "iso3n", nomatch = NULL),
    year = TIME,
    taxrev = Value
  ) %>%
  arrange(cntry,year) %>%
  dplyr::select(cntry,year,taxrev) %>%
  filter(year %in% c(2010,2014)& cntry %in% seat$cntry) %>%
  mutate(
    wave = year
  )

``` 

## GDP
```{r gdp, include=TRUE, message=FALSE}
gdp <- gdp %>%
  mutate(
    GEO = car::recode(GEO, '"Germany (until 1990 former territory of the FRG" = "Germany"'),
    cntry = countrycode(GEO, origin = "country.name", destination = "iso3n", nomatch = NULL),
    year = TIME,
    gdp = Value
  ) %>%
  arrange(cntry,year) %>%
  dplyr::select(cntry,year,gdp) %>%
  filter(year %in% c(2010,2014)& cntry %in% seat$cntry) %>%
  mutate(
    wave = year
  )

``` 


## Environment mean 

```{r env2}

# Back to environment 

env <- env[which(env$cntry %in% govpos$cntry),]
env <- env[complete.cases(env$price),]
env <- env[complete.cases(env$tax),]
env <- env[complete.cases(env$cut),]

# Environment new 
env$tradeoff <- round(rowMeans(env[,-c(1,2,6)]),2)

env_mean <- round(aggregate(env, by = list(env$cntry, env$wave), FUN = mean, na.rm = T),2)
env_sd <- round(aggregate(env, by = list(env$cntry,env$wave), FUN = sd, na.rm = T),2)

env_mean <- env_mean %>%
  mutate(
    cntry = Group.1,
    wave = Group.2,
    year = ifelse(wave == 2010, 2000, 2010),
    price_mean = price,
    tax_mean = tax,
    cut_mean = cut,
  ) %>%
  dplyr::select(cntry,year, wave,price_mean,tax_mean,cut_mean, tradeoff) %>%
  arrange(cntry,wave)

env_sd <- env_sd %>%
  mutate(
    cntry = Group.1,
    wave = Group.2,
    year = ifelse(wave == 2010, 2000, 2010),
    price_sd = price,
    tax_sd = tax,
    cut_sd = cut,
    tradeoff_sd = tradeoff
  ) %>%  
  dplyr::select(cntry,year, wave, price_sd,tax_sd,cut_sd, tradeoff_sd) %>%
  arrange(cntry,wave)


df = left_join(govpos,env_mean, by = c("cntry","wave"))
df = left_join(df, gspend, by = c("cntry","wave"))
df = left_join(df, gtax, by = c("cntry","wave"))



```

## Deal with CO2 Emissions

```{r co2}
co2$freq.geo.TIME_PERIOD <- substr(co2$freq.geo.TIME_PERIOD,3,4)
co2 <- co2 %>%
  mutate(
    cntry = car::recode(freq.geo.TIME_PERIOD, '"EL" = "GR"; "UK" = "GB"'),
    cname = countrycode(cntry, origin = "iso2c", destination = "country.name", nomatch = NULL)
  )

co2.2 <- as.data.frame(matrix(nrow = 70,ncol = 3))
co2.2 <- co2.2 %>%
  mutate(
    cname = rep(co2$cname,2),
    co2 = V1,
    year = V2
  ) %>%
  dplyr::select(cname,co2,year)

co2.2[1:35,]$co2 <- co2$X2010
co2.2[36:70,]$co2 <- co2$X2014
co2.2[1:35,]$year <- 2010
co2.2[36:70,]$year <- 2014
co2.2$wave <- co2.2$year

co2 <- co2.2
co2 <- arrange(co2, cname,wave)
co2$cntry <- countrycode(co2$cname, origin = "country.name", destination = "iso3n", nomatch = NULL)

co2 <- co2[which(co2$cntry %in% govpos$cntry), ]
co2[which(co2$cname == "France" & co2$wave == 2014),]$co2 <- 7.1

co2$co2 <- as.numeric(co2$co2)
df = left_join(df, co2, by = c("cntry", "wave"))
df <- dplyr::select(df,cntry, wave, year.x, price_mean, tax_mean, cut_mean,govpos, tradeoff, spend, taxrev, co2)
colnames(df) [3] <- "year"
```



## Descriptive statistics - Basic visualizations

```{r dessta}
# Summarise the Environment dataset - Table 1 


library(sjmisc)
descr(env,show = c("n", "mean", "sd", "range", "skew"),out = "browser")
descr(df,show = c("n", "mean", "sd", "range", "skew"),out = "browser")

# Plot mean opinion by country - Figure 1
env_mean2 <- env_mean
env_mean2$cntry <- as.factor(env_mean$cntry)
env_mean2$cname <- countrycode(env_mean2$cntry, origin = "iso3n", destination = "country.name")

agg_png("Fig1.png", width = 1200, height = 700, res = 144)
ggplot(data = env_mean2, aes(x = year, y = tradeoff, color = cname)) +
  geom_point(size = 2,)+
  geom_line() + 
  labs(title = "Willingness to sacrifice for environment protection by country", color = "Country") +
  ylab(label = "Mean Willingness") +
  xlab(label = "Year") +
  scale_x_continuous(breaks = c(2000,2010)) +
  theme(plot.title = element_text(size = 15,face = "bold"))
invisible(dev.off())

# Party
party[,-c(1:4)] <- round(party[,-c(1:4)],2)
party$cname <- countrycode(party$cntry, origin = "iso3n", destination = "country.name")

party2 <- party[,c(9,2,4,6:8)]
colnames(party2) <- c("Country", "Year", "Party name", "Attitude", "Percentage Seat", "Gov Position")
party2 %>% gt()

# Plot mean position by country - Figure 2

govpos2 <- govpos
govpos2$govpos <- round(govpos2$govpos,2)
govpos2$cname <- countrycode(govpos2$cntry, origin = "iso3n", destination = "country.name")
govpos2 <- govpos2[,c(5,2,4)]
colnames(govpos2) <- c("Country", "Year", "Goverment position")
descr(govpos2$`Goverment position`, show = c("n", "mean", "sd", "range", "skew"),out = "browser" )



govpos$cntry <- as.factor(govpos$cntry)
govpos$cname <- countrycode(govpos$cntry, origin = "iso3n", destination = "country.name")

agg_png(filename = "Fig2.png", width = 1200, height = 700, res =144,)
ggplot(data = govpos, aes(x = year, y = govpos, color = cname)) +
  geom_point(size = 2)+
  geom_line() + 
  labs(title = "Party positions by country", color = "Country") +
  ylab(label = "Mean Party Position") +
  xlab(label = "Year") +
  theme(plot.title = element_text(size = 15,face = "bold"))

invisible(dev.off())

# Spending 
gspend$spend <- as.numeric(gspend$spend)
descr(gspend, show = c("n", "mean", "sd", "range", "skew"),out = "browser")
gspend$cname <- countrycode(gspend$cntry, origin = "iso3n", destination = "country.name")
gspend2 <- gspend[,c(5,2,3)]


agg_png(filename = "Fig3.png", width = 1200, height = 700, res =144,)
ggplot(data = gspend2, aes(x = year, y = spend, color = cname)) +
  geom_point(size = 2)+
  geom_line() + 
  labs(title = "Government Spending on environment protection by country", color = "Country") +
  ylab(label = "As Percentage of Total Spending") +
  xlab(label = "Year") +
  theme(plot.title = element_text(size = 15,face = "bold"))

invisible(dev.off())


# Tax revenue

gtax$taxrev <- as.numeric(gtax$taxrev)
descr(gtax, show = c("n", "mean", "sd", "range", "skew"),out = "browser")
gtax$cname <- countrycode(gtax$cntry, origin = "iso3n", destination = "country.name")
gtax2 <- gtax[,c(5,2,3)]

agg_png(filename = "Fig4.png", width = 1200, height = 700, res =144,)
ggplot(data = gtax2, aes(x = year, y = taxrev, color = cname)) +
  geom_point(size = 2)+
  geom_line() + 
  labs(title = "Government Environment Tax Revenue by country", color = "Country") +
  ylab(label = "As Percentage of Total Revenue") +
  xlab(label = "Year") +
  theme(plot.title = element_text(size = 15,face = "bold"))

invisible(dev.off())

# Measurement model


mod1 <- '
  # cfa
  pubop =~ price + tax + cut
'

fit1 <- cfa(mod1, data = env)

mod1coef <-parameterEstimates(fit1, standardized=TRUE)[,c(1:2,5:9,12)] %>% filter(op == "=~")

mod1coef[,1] <- "Willingness to trade"
mod1coef[,2] <- c("Price", "Tax", "Cut")
mod1coef[,-c(1:2)] <- round(mod1coef[,-c(1,2)],3)
colnames(mod1coef) <- c("Latent", "Observed Variables", "SE", "Z", "P-Value", "CI.Lower", "CI.Upper", "Standardized Factor Loadings")

library(gt)
mod1coef %>% gt()

mod1var <- parameterEstimates(fit1, standardized=TRUE)[,c(1:2,5:9,12)] %>% filter(op == "~~")
mod1var <- mod1var[-4,-2]
mod1var[,-1] <- round(mod1var[,-1],3)

colnames(mod1var) <- c("Variable", "SE", "Z", "P-Value", "CI.Lower", "CI.Upper", "Standardized Error Variance")
mod1var$r2 <- round(inspect(fit1, what = "r2"),3)

mod1var %>% gt()

mod1fit <- data.frame(
  CFI = fitmeasures(fit1, "cfi"),
  TLI = fitmeasures(fit1, "tli"),
  RMSEA = fitmeasures(fit1, "RMSEA"),
  AIC = round(fitmeasures(fit1, "AIC"),0),
  BIC = round(fitmeasures(fit1, "BIC"),0),
  Chisquared = round(fitmeasures(fit1, "chisq"),3)
)

mod1fit %>% gt()


# Configural invariance across time and space


configural <- cfa (mod1, data = env, group = "cntry", estimator = "ML")

summary (configural, fit.measures = TRUE, standardized = TRUE, rsq = TRUE)

config1fit <- data.frame(
  CFI = fitmeasures(configural, "cfi"),
  TLI = fitmeasures(configural, "tli"),
  RMSEA = fitmeasures(configural, "RMSEA"),
  AIC = round(fitmeasures(configural, "AIC"),0),
  BIC = round(fitmeasures(configural, "BIC"),0),
  Chisquared = round(fitmeasures(configural, "chisq"),3)
)
weak <- cfa (mod1, data = env, group = "cntry",
group.equal = "loadings", estimator = "ML")

strong <- cfa (mod1, data = env, group = "cntry",
group.equal = c("loadings", "intercepts"), estimator = "ML")

strict <- cfa (mod1, data = env, group = "cntry",
group.equal = c("loadings", "intercepts","residuals"), estimator = "ML")

meaIn1 <- anova(configural,weak,strong,strict)



configural2 <- cfa (mod1, data = env, group = "year", estimator = "ML")

summary (configural2, fit.measures = TRUE, standardized = TRUE, rsq = TRUE)

config2fit <- data.frame(
  CFI = fitmeasures(configural2, "cfi"),
  TLI = fitmeasures(configural2, "tli"),
  RMSEA = fitmeasures(configural2, "RMSEA"),
  AIC = round(fitmeasures(configural2, "AIC"),0),
  BIC = round(fitmeasures(configural2, "BIC"),0),
  Chisquared = round(fitmeasures(configural2, "chisq"),3)
)
weak2 <- cfa (mod1, data = env, group = "year",
group.equal = "loadings", estimator = "ML")

strong2 <- cfa (mod1, data = env, group = "year",
group.equal = c("loadings", "intercepts"), estimator = "ML")

strict2 <- cfa (mod1, data = env, group = "year",
group.equal = c("loadings", "intercepts","residuals"), estimator = "ML")

meaIn2 <- anova(configural2,weak2,strong2,strict2)

config1fit %>% gt()
meaIn1 <- round(meaIn1,3)

meaIn1 %>% gt(rowname_col = TRUE)

config2fit %>% gt()

meaIn2 <- round(meaIn2,3)

meaIn2 %>% gt()


```

## Analysis


```{r}

df <- left_join(df, gdp, by = c("cntry","wave"))
df$gdp <- gsub(',','',df$gdp)
df$taxrev <- gsub(',','',df$taxrev)

df <- df %>%
  select(cntry, wave, tradeoff, taxrev, spend, govpos, co2, gdp) %>%
  mutate(
    taxrev = as.numeric(taxrev),
    spend = as.numeric(spend),
    gdp = as.numeric(gdp),
    govpos = round(govpos,2),
    year1 = ifelse(wave == 2010, 2000, 2010),
    year2 = wave
  )

# Dependent variable: Spending
# Model 1: whether public opinion  predicts spending


model1 <- "
  # regression
  spend ~ tradeoff + cntry + wave 
"
m1 <- sem(model1, df, se = "bootstrap")


summary(m1, fit.measures = TRUE, rsquare = TRUE)

model1.2 <- "
  # regression
  spend ~ tradeoff + cntry + wave + co2
"
m1.2 <- sem(model1.2, df, se = "bootstrap")

summary(m1.2, fit.measures = TRUE, rsquare = TRUE)

model1.3 <- "
  # regression
  spend ~ tradeoff + cntry + wave + gdp
"
m1.3 <- sem(model1.3, df, se = "bootstrap", check.gradient = FALSE)

summary(m1.3, fit.measures = TRUE, rsquare = TRUE)

model1.4 <- "
  # regression
  spend ~ tradeoff + cntry + wave + co2 + gdp
"
m1.4 <- sem(model1.4, df, se = "bootstrap", check.gradient = FALSE)

summary(m1.4, fit.measures = TRUE, rsquare = TRUE)




tabmod1 <- data.frame(
  matrix(nrow = 10, ncol = 4),
  row.names = c("Willingness", "Country", "Year","CO2", "GDP", "Observations","R-squared", "AIC", "BIC", "log-likelihood")
)
colnames(tabmod1) <- c("M11", "M12", "M13", "M14")
tabmod1[,1] <- c("-0.167","0.001*", "0.040","","",32,"0.096","58.052","63.915","-25.026")
tabmod1[,2] <- c("-0.207","0.001*", "0.044","0.015","",32,"0.099","59.962","67.290","-24.981")
tabmod1[,3] <- c("0.271","0.001*", "0.058","","-0.000",32,"0.140","58.462","65.791","-24.231")
tabmod1[,4] <- c("0.229","0.001*", "0.064","0.021","-0.000",32,"0.145","60.272","69.067","-24.136")

## Table 1 

tab1 <- gt(data = tabmod1,rowname_col = TRUE, rownames_to_stub = TRUE) %>%
  tab_header(
    title = md("**Main Regression Models Regressing Government Spending on Willingness** ")
  ) %>%
  tab_footnote(
    footnote = " *** p < 0.01 ** p < 0.05 * p < 0.1 *",
    locations = cells_body(
      columns = vars(M12),
      rows = 2)
  )


# Model 2: whether public opinion predicts party position
model2 <- "
  # regression
  govpos ~ tradeoff + cntry + wave
"
m2 <- sem(model2, df, se = "bootstrap")

summary(m2, fit.measures = TRUE, rsquare = TRUE, standardized = TRUE)

model2.2 <- "
  # regression
  govpos ~ tradeoff + cntry + wave + co2
"

m2.2 <- sem(model2.2, df, se = "bootstrap")

summary(m2.2, fit.measures = TRUE, rsquare = TRUE)

model2.3 <- "
  # regression
  govpos ~ tradeoff + cntry + wave + gdp
"
m2.3 <- sem(model2.3, df, se = "bootstrap", check.gradient = FALSE)

summary(m2.3, fit.measures = TRUE, rsquare = TRUE)

model2.4 <- "
  # regression
  govpos ~ tradeoff + cntry + wave + co2 + gdp
"
m2.4 <- sem(model2.4, df, se = "bootstrap", check.gradient = FALSE)

summary(m2.4, fit.measures = TRUE, rsquare = TRUE,standardized = TRUE)


tabmod2 <- data.frame(
  matrix(nrow = 10, ncol = 4),
  row.names = c("Willingness", "Country", "Year","CO2", "GDP", "Observations","R-squared", "AIC", "BIC", "log-likelihood")
)
colnames(tabmod2) <- c("M21", "M22", "M23", "M24")
tabmod2[,1] <- c("-1.210**","0.000", "-0.062","","",32,"0.134","106.782","112.645","-49.391")
tabmod2[,2] <- c("-1.511**","0.000", "-0.034","0.109","",32,"0.163","107.684","115.013","-48.842")
tabmod2[,3] <- c("-1.713**","-0.001", "-0.083","","0.000",32,"0.146","108.333","115.662","-49.167")
tabmod2[,4] <- c("-1.925**","-0.000", "-0.053","0.103","0.000",32,"0.172","109.349","118.143","-48.674")
## Table 2
tab2 <- gt(data = tabmod2,rowname_col = TRUE, rownames_to_stub = TRUE) %>%
  tab_header(
    title = md("**Main Regression Models Regressing Government Position on Willingness** ")
  ) %>%
  tab_footnote(
    footnote = " *** p < 0.01 ** p < 0.05 * p < 0.1 *",
    locations = cells_body(
      columns = vars(M21),
      rows = 1)
    
  )

# SEM 1: Public Opinion - Party Positions - Government Spending

modsem1 <- "
# direct effect
  spend ~ c*tradeoff + cntry
# mediator
  govpos ~ a*tradeoff + co2 + gdp
  spend ~ b*govpos 
# total effect
  total := c + (a*b)
"
m4 <- sem(modsem1,df, se = "bootstrap", check.gradient = FALSE)

summary(m4, fit.measures = TRUE, rsquare = TRUE, standardized = TRUE)

tabmod4 <- data.frame(
  matrix(nrow = 6, ncol = 3),
  row.names = c("Willingness", "Government Position", "R2-Spend", "R2-GovPos", "Observations","Total Effect")
)
colnames(tabmod4) <- c("X predicting Y", "X predicting M", "M predicting Y")
tabmod4[,1] <- c("-0.370","","0.100","0.124","32","-0.201")
tabmod4[,2] <- c("-1.228***","","-0.001","","","")
tabmod4[,3] <- c("","0.074","","","","")

## Table 4
tab4 <- gt(data = tabmod4,rowname_col = TRUE, rownames_to_stub = TRUE) %>%
  tab_header(
    title = md("**Full SEM-Mediation Model Testing the Total Effect of Willingness on Spending** ")
  ) %>%
  tab_footnote(
    footnote = " *** p < 0.01 ** p < 0.05 * p < 0.1 *",
    locations = cells_body(
      columns = 3,
      rows = 1)
  )


# Dependent variable: Tax

# Model 4: whether public opinion  predicts tax revenue

model4 <- "
  # regression
  taxrev ~ tradeoff + cntry + wave 
"
m4 <- sem(model4, df, se = "bootstrap")

summary(m4, fit.measures = TRUE, rsquare = TRUE)


model4.2 <- "
  # regression
  taxrev ~ tradeoff + cntry + wave + co2
"
m4.2 <- sem(model4.2, df, se = "bootstrap")

summary(m4.2, fit.measures = TRUE, rsquare = TRUE, standardized = TRUE)



model4.3 <- "
  # regression
  taxrev ~ tradeoff + cntry + wave + gdp
"
m4.3 <- sem(model4.3, df, se = "bootstrap", check.gradient = FALSE)

summary(m4.3, fit.measures = TRUE, rsquare = TRUE, standardized = TRUE)


model4.4 <- "
  # regression
  taxrev ~ tradeoff + cntry + wave + co2 + gdp
"
m4.4 <- sem(model4.4, df, se = "bootstrap", check.gradient = FALSE)

summary(m4.4, fit.measures = TRUE, rsquare = TRUE)


tabmod4 <- data.frame(
  matrix(nrow = 10, ncol = 4),
  row.names = c("Willingness", "Country", "Year","CO2", "GDP", "Observations","R-squared", "AIC", "BIC", "log-likelihood")
)

colnames(tabmod4) <- c("M31", "M32", "M33", "M34")
tabmod4[,1] <- c("-1.729","0.000", "-0.161","","",32,"0.105","135.451","141.314","-63.726")
tabmod4[,2] <- c("-1.678","0.000", "-0.165","-0.018","",32,"0.106","137.439","144.767","-63.719")
tabmod4[,3] <- c("1.003","0.000", "-0.050","","-0.000**",32,"0.255","131.574","138.902","-60.787")
tabmod4[,4] <- c("0.963","0.000", "-0.045","0.019","-0.000**",32,"0.256","133.557","142.352","-60.779")

## Table 4 
tab4 <- gt(data = tabmod4,rowname_col = TRUE, rownames_to_stub = TRUE) %>%
  tab_header(
    title = md("**Main Regression Models Regressing Government Tax Revenue on Willingness** ")
  ) %>%
  tab_footnote(
    footnote = " *** p < 0.01 ** p < 0.05 * p < 0.1 *",
    locations = cells_body(
      columns = vars(M33),
      rows = 5)
  )



## SEM 2 - Public Opinion - Party Positions - Tax Revenue
### Country from East and West as binary variable
df <- df %>%
  mutate(
    cname = countrycode(cntry, origin = "iso3n", destination = "country.name"),
    east = ifelse(cname %in% c("Bulgaria","Czechia","Latvia","Slovenia", "Slovakia"), 1, 0)
  )
df$east <- as.numeric(df$east)

modsem2 <- "
# direct effect
  taxrev ~ c*tradeoff + east
# mediator
  govpos ~ a*tradeoff + co2 + gdp 
  taxrev ~ b*govpos 
# total effect
  total := c + (a*b)
  indirect := a*b
"

m6 <- sem(modsem2,df, se = "bootstrap", check.gradient = FALSE)

summary(m6, fit.measures = TRUE, rsquare = TRUE, standardized = TRUE)


tabmod6 <- data.frame(
  matrix(nrow = 7, ncol = 3),
  row.names = c("Willingness", "Government Position", "GDP","R2-TaxRev", "R2-GovPos", "Observations","Total Effect")
)
colnames(tabmod6) <- c("X predicting Y", "X predicting M", "M predicting Y")
tabmod6[,1] <- c("1.738","","-0.000***","0.314","0.113","32","1.282")
tabmod6[,2] <- c("-1.227**","","","","","","")
tabmod6[,3] <- c("","0.372","","","","","")

## Table 6
tab6 <- gt(data = tabmod6,rowname_col = TRUE, rownames_to_stub = TRUE) %>%
  tab_header(
    title = md("**Full SEM-Mediation Model Testing the Total Effect of Willingness on Tax Revenue** ")
  ) %>%
  tab_footnote(
    footnote = " *** p < 0.01 ** p < 0.05 * p < 0.1 *",
    locations = cells_body(
      columns = 3,
      rows = 1)
  )

# 2014 only
df1 <- df[which(df$wave == 2014),]
df2 <- na.omit(df[which(df$wave == 2010),])

cor1 <- select(df1, cntry, gdp, co2, tradeoff, taxrev)
cor2 <- select(df2, cntry, gdp,co2, tradeoff, taxrev)
cor3 <- na.omit(select(df, cntry, wave, gdp, co2, tradeoff, taxrev))
cor1mat <- data.frame(round(cor(cor1,cor1),3),row.names = c("Country", "GDP", "CO2", "Willingness", "Tax Revenue"))
cor2mat <- data.frame(round(cor(cor2,cor2),3),row.names = c("Country", "GDP", "CO2", "Willingness", "Tax Revenue"))
cor3mat <- data.frame(round(cor(cor3,cor3),3),row.names = c("Country","Year", "GDP", "CO2", "Willingness", "Tax Revenue"))


model7 <- "
  # regression
  govpos ~ tradeoff + cntry 
"
m7 <- sem(model7, df1, se = "bootstrap")

summary(m7, fit.measures = TRUE, rsquare = TRUE)


model7.2 <- "
  # regression
  govpos ~ tradeoff + cntry + co2
"
m7.2 <- sem(model7.2, df1, se = "bootstrap")

summary(m7.2, fit.measures = TRUE, rsquare = TRUE)


model7.3 <- "
  # regression
  govpos ~ tradeoff + cntry + gdp
"
m7.3 <- sem(model7.3, df1, se = "bootstrap", check.gradient = FALSE)

summary(m7.3, fit.measures = TRUE, rsquare = TRUE)


model7.4 <- "
  # regression
  govpos ~ tradeoff + cntry + co2 + gdp
"
m7.4 <- sem(model7.4, df1, se = "bootstrap", check.gradient = FALSE)

summary(m7.4, fit.measures = TRUE, rsquare = TRUE)


tabmod7 <- data.frame(
  matrix(nrow = 9, ncol = 4),
  row.names = c("Willingness", "Country", "CO2", "GDP", "Observations","R-squared", "AIC", "BIC", "log-likelihood")
)

colnames(tabmod7) <- c("M41", "M42", "M43", "M44")
tabmod7[,1] <- c("-1.871**","0.000", "","",17,"0.219","60.043","62.542","-27.021")
tabmod7[,2] <- c("-1.922*","0.000", "0.026","",17,"0.220","62.018","65.351","-27.009")
tabmod7[,3] <- c("-3.152**","0.000", "","0.000",17,"0.269","60.913","64.246","-26.457")
tabmod7[,4] <- c("-3.190*","0.000", "0.021","0.000",17,"0.270","62.896","67.062","-26.448")

## Table 7 
tab7 <- gt(data = tabmod7,rowname_col = TRUE, rownames_to_stub = TRUE) %>%
  tab_header(
    title = md("**Main Regression Models Regressing Government Position on Willingness** ")
  ) %>%
  tab_footnote(
    footnote = " *** p < 0.01 ** p < 0.05 * p < 0.1 *",
    locations = cells_body(
      columns = vars(M41),
      rows = 1)
  )

# Model 5: whether public opinion  predicts tax revenue

model8 <- "
  # regression
  taxrev ~ tradeoff + cntry 
"
m8 <- sem(model8, df1, se = "bootstrap")

summary(m8, fit.measures = TRUE, rsquare = TRUE)


model8.2 <- "
  # regression
  taxrev ~ tradeoff + cntry + co2
"
m8.2 <- sem(model8.2, df1, se = "bootstrap", check.gradient = FALSE)

summary(m8.2, fit.measures = TRUE, rsquare = TRUE)



model8.3 <- "
  # regression
  taxrev ~  gdp
"
m8.3 <- sem(model8.3, df1, se = "bootstrap")

summary(m8.3, fit.measures = TRUE, rsquare = TRUE)


model8.4 <- "
  # regression
  taxrev ~ tradeoff + cntry + co2 + gdp
"
m8.4 <- sem(model8.4, df1, se = "bootstrap", check.gradient = FALSE)

summary(m8.4, fit.measures = TRUE, rsquare = TRUE)

tabmod8 <- data.frame(
  matrix(nrow = 9, ncol = 4),
  row.names = c("Willingness", "Country", "CO2", "GDP", "Observations","R-squared", "AIC", "BIC", "log-likelihood")
)

colnames(tabmod8) <- c("M51", "M52", "M53", "M54")
tabmod8[,1] <- c("-2.307","0.001", "","",17,"0.157","73.933","76.432","-33.966")
tabmod8[,2] <- c("-2.420","0.001", "0.057","",17,"0.160","75.880","79.213","-33.940")
tabmod8[,3] <- c("-0.031","0.001", "","0.000",17,"0.233","74.336","77.669","-33.168")
tabmod8[,4] <- c("-0.146","0.001", "0.065","0.000",17,"0.236","76.261","80.427","-33.130")

## Table 8
tab8 <- gt(data = tabmod8,rowname_col = TRUE, rownames_to_stub = TRUE) %>%
  tab_header(
    title = md("**Main Regression Models Regressing Tax Revenue on Willingness** ")
  ) %>%
  tab_footnote(
    footnote = " *** p < 0.01 ** p < 0.05 * p < 0.1 *",
    locations = cells_body(
      columns = vars(M51),
      rows = 1)
  )


# SEM 3: Public Opinion - Party Positions - Tax Revenue (only 2014)
modsem3 <- "
# direct effect
  taxrev ~ c*tradeoff + east
# mediator
  govpos ~ a*tradeoff + co2 + gdp 
  taxrev ~ b*govpos 
# total effect
  total := c + (a*b)
  indirect := a*b
"

m9 <- sem(modsem3,df1, se = "bootstrap", check.gradient = FALSE)

summary(m9, fit.measures = TRUE, rsquare = TRUE, standardized  = TRUE)


tabmod9 <- data.frame(
  matrix(nrow = 6, ncol = 3),
  row.names = c("Willingness", "Government Position", "R2-TaxRev", "R2-GovPos", "Observations","Total Effect")
)
colnames(tabmod9) <- c("X predicting Y", "X predicting M", "M predicting Y")
tabmod9[,1] <- c("-1.619","","0.188","0.216","17","-2.203")
tabmod9[,2] <- c("-1.829**","","","","","")
tabmod9[,3] <- c("","0.319","","","","")

## Table 9
tab9 <- gt(data = tabmod9,rowname_col = TRUE, rownames_to_stub = TRUE) %>%
  tab_header(
    title = md("**Full SEM-Mediation Model Testing the Total Effect of Willingness on Tax Revenue, 2014**")
  ) %>%
  tab_footnote(
    footnote = " *** p < 0.01 ** p < 0.05 * p < 0.1 *",
    locations = cells_body(
      columns = 3,
      rows = 1)
  )
```


## Additional models
```{r}
# Whether government positions predicts spending

model3 <- "
  # regression
  spend ~ govpos + cntry + wave 
"
m3 <- sem(model3, df)

summary(m3, fit.measures = TRUE, rsquare = TRUE)


model3.2 <- "
  # regression
  spend ~ govpos + cntry + wave + co2 
"
m3.2 <- sem(model3.2, df)

summary(m3.2, fit.measures = TRUE, rsquare = TRUE)


model3.3 <- "
  # regression
  spend ~ govpos + cntry + wave + gdp
"
m3.3 <- sem(model3.3, df)

summary(m3.3, fit.measures = TRUE, rsquare = TRUE)


model3.4 <- "
  # regression
  spend ~ govpos + cntry + wave + co2 + gdp
"
m3.4 <- sem(model3.4, df)

summary(m3.4, fit.measures = TRUE, rsquare = TRUE)


tabmod3 <- data.frame(
  matrix(nrow = 10, ncol = 4),
  row.names = c("Government Position", "Country", "Year","CO2", "GDP", "Observations","R-squared", "AIC", "BIC", "log-likelihood")
)
colnames(tabmod3) <- c("M1", "M2", "M3", "M4")
tabmod3[,1] <- c("0.104","0.001*", "0.039","","",32,"0.144","59.007","65.112","-25.503")
tabmod3[,2] <- c("0.104","0.001*", "0.039","-0.002","",32,"0.144","61.004","68.636","-25.502")
tabmod3[,3] <- c("0.104","0.001*", "0.039","","0.000",32,"0.144","61.006","68.638","-25.503")
tabmod3[,4] <- c("0.104","0.001*", "0.039","-0.003","0.000",32,"0.144","63.003","72.161","-25.501")

tab3 <- gt(data = tabmod3,rowname_col = TRUE, rownames_to_stub = TRUE) %>%
  tab_header(
    title = md("**Main Regression Models Testing the Relationship of Government Position and Government Spending** ")
  ) %>%
  tab_footnote(
    footnote = " *** p < 0.01 ** p < 0.05 * p < 0.1 *",
    locations = cells_body(
      columns = vars(M1),
      rows = 2)
  )



# Whether government positions predicts tax revenue

model5 <- "
  # regression
  taxrev ~ govpos + cntry + wave 
"
m5 <- sem(model5, df)

summary(m5, fit.measures = TRUE, rsquare = TRUE)


model5.2 <- "
  # regression
  taxrev ~ govpos + cntry + wave + co2
"
m5.2 <- sem(model5.2, df)

summary(m5.2, fit.measures = TRUE, rsquare = TRUE)


model5.3 <- "
  # regression
  taxrev ~ govpos + cntry + wave + gdp
"
m5.3 <- sem(model5.3, df)

summary(m5.3, fit.measures = TRUE, rsquare = TRUE)


model5.4 <- "
  # regression
  taxrev ~ govpos + cntry + wave + co2 + gdp
"
m5.4 <- sem(model5.4, df)

summary(m5.4, fit.measures = TRUE, rsquare = TRUE)


## Comparing East-West/ Rich-Poor
df <- df %>%
  mutate(
    gdp_scale = round(scale(gdp),2),
    topgdp = ifelse(gdp_scale>=1, 1, 0)
  )
m10 <- lm(spend ~ tradeoff + as.factor(east) + as.factor(wave), data = df )
m10.2 <- lm(spend ~ tradeoff + as.factor(east) + as.factor(wave) + co2, data = df )
m10.3 <- lm(spend ~ tradeoff + as.factor(east) + as.factor(wave) + gdp, data = df )
m10.4 <- lm(spend ~ tradeoff + as.factor(east) + as.factor(wave) + co2 + gdp, data = df )

tab_model(m10, m10.2, m10.3, m10.4, p.style = "stars", p.threshold = c(0.10, 0.05, 0.01), show.ci = F, rm.terms = c("(Intercept)"), show.loglik = T, show.aic = T, dv.labels = c("M11a", "M12a","M13a", "M14a"), pred.labels = c("Willingness", "East", "Year/Wave", "CO2", "GDP") ,file = "Table10.html",show.std = TRUE)

m11 <- lm(taxrev ~ tradeoff + as.factor(east) + as.factor(wave), data = df)
m11.2 <- lm(taxrev ~ tradeoff + as.factor(east) + as.factor(wave) + co2, data = df)
m11.3 <- lm(taxrev ~ tradeoff + as.factor(east) + as.factor(wave) + gdp, data = df)
m11.4 <- lm(taxrev ~ tradeoff + as.factor(east) + as.factor(wave) + co2 + gdp, data = df)

tab_model(m11, m11.2, m11.3, m11.4, p.style = "stars", p.threshold = c(0.10, 0.05, 0.01), show.ci = F, rm.terms = c("(Intercept)"), show.loglik = T, show.aic = T, show.std = TRUE, dv.labels = c("M31a", "M32a","M33a", "M34a"), pred.labels = c("Willingness", "East", "Year/Wave", "CO2", "GDP") ,file = "Table11.html")



# Validity check - data 2014

## East on Tax Revenue
df1 <- df[which(df$wave == 2014),]

m12 <- lm(taxrev ~ tradeoff + as.factor(east), data = df1)
m12.2 <- lm(taxrev ~ tradeoff + as.factor(east)  + co2, data = df1)
m12.3 <- lm(taxrev ~ tradeoff + as.factor(east) + gdp, data = df1)
m12.4 <- lm(taxrev ~ tradeoff + as.factor(east) + co2 + gdp, data = df1)

tab_model(m12, m12.2, m12.3, m12.4, p.style = "stars", p.threshold = c(0.10, 0.05, 0.01), show.ci = F, rm.terms = c("(Intercept)"), show.loglik = T, show.aic = T, show.std = TRUE, dv.labels = c("M41", "M42","M43", "M44"), pred.labels = c("Willingness", "East", "CO2", "GDP") ,file = "Table12.html")

## Willingness - Government Position

m13 <- lm(govpos ~ tradeoff + cntry, data = df1)
m13.2 <- lm(govpos ~ tradeoff + cntry  + co2, data = df1)
m13.3 <- lm(govpos ~ tradeoff + cntry + gdp, data = df1)
m13.4 <- lm(govpos ~ tradeoff + cntry + co2 + gdp, data = df1)

tab_model(m13, m13.2, m13.3, m13.4, p.style = "stars", p.threshold = c(0.10, 0.05, 0.01), show.ci = F, rm.terms = c("(Intercept)"), show.loglik = T, show.aic = T, show.std = TRUE, dv.labels = c("M51", "M52","M53", "M54"), pred.labels = c("Willingness", "Country", "CO2", "GDP") ,file = "Table13.html")

cor(df2$gdp,df2$cntry)


a.6 <- lm(gdp~ east, data = df)

tab_model(a.6, p.style = "stars", p.threshold = c(0.10, 0.05, 0.01), show.ci = F, rm.terms = c("(Intercept)"), show.loglik = T, show.aic = T, show.std = TRUE, dv.labels = c("Predicting GDP"), pred.labels = c("East") ,file = "A5.html")
```

